development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: capi_development
  pool: 5
  username: root
  password:

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
